services:
  napcat:
    image: ghcr.io/napneko/nodenapcat:latest
    container_name: napcat
    restart: unless-stopped
    network_mode: host
    volumes:
      - /opt/napcat/QQ:/app/.config/QQ
      - /opt/napcat/config:/app/napcat/config
