services:
  napcat:
    image: ghcr.io/napneko/nodenapcat:latest
    container_name: napcat
    restart: unless-stopped
    network_mode: host
    mem_limit: 256m
    environment:
      - NAPCAT_QUICK_ACCOUNT=${NAPCAT_QUICK_ACCOUNT:-1270667498}
    volumes:
      - /opt/napcat/QQ:/root/.config/QQ
      - /opt/napcat/config:/app/napcat/config
